In [1]:
from IPython.display import Image
import numpy as np
import pandas as pd

In [2]:
Image(url='https://scikit-learn.org/stable/_static/ml_map.png')

In [3]:
hd = pd.read_html('https://github.com/mrdbourke/zero-to-mastery-ml/blob/master/data/heart-disease.csv')

In [4]:
data = hd[0].iloc[:,1:]

In [5]:
data.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       303 non-null    int64  
 1   sex       303 non-null    int64  
 2   cp        303 non-null    int64  
 3   trestbps  303 non-null    int64  
 4   chol      303 non-null    int64  
 5   fbs       303 non-null    int64  
 6   restecg   303 non-null    int64  
 7   thalach   303 non-null    int64  
 8   exang     303 non-null    int64  
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64  
 11  ca        303 non-null    int64  
 12  thal      303 non-null    int64  
 13  target    303 non-null    int64  
dtypes: float64(1), int64(13)
memory usage: 33.3 KB


In [7]:
#Choosing  LinearSVC with the help of decision tree provided by scikit learn 

In [8]:
from sklearn.svm import LinearSVC
from sklearn.model_selection import train_test_split

In [9]:
np.random.seed(1)

featured_x = data.drop('target',axis=1)

label_y = data['target']


x_train,x_test,y_train,y_test = train_test_split(featured_x,label_y,test_size=0.2)

clf = LinearSVC(max_iter=10000)

clf.fit(x_train,y_train)

clf.score(x_test,y_test)

C:\Users\Nill\AppData\Roaming\Python\Python37\site-packages\sklearn\svm\_base.py:977: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


0.7704918032786885

In [10]:
####

In [11]:
data['target'].value_counts()

1    165
0    138
Name: target, dtype: int64

In [12]:
## RandomForestClassifier

In [13]:
from sklearn.ensemble import RandomForestClassifier

In [14]:
np.random.seed(2)

featured_x2 = data.drop('target',axis=1)

label_y2 = data['target']

x2_train,x2_test,y2_train,y2_test = train_test_split(featured_x2,label_y2,test_size=0.2)

clf2 = RandomForestClassifier()

clf2.fit(x2_train,y2_train)

clf2.score(x2_test,y2_test)

0.8852459016393442

In [15]:
#### 

## Prediction (If someone has heart disease or not)

In [16]:
#predict() or #predict_proba()

In [17]:
##

In [18]:
##

In [19]:
#### predict()

In [20]:
x2_test.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
99    53    1   2       130   246    1        0      173      0      0.0   
296   63    0   0       124   197    0        1      136      1      0.0   
89    58    0   0       100   248    0        0      122      0      1.0   
30    41    0   1       105   198    0        1      168      0      0.0   
234   70    1   0       130   322    0        0      109      0      2.4   

     slope  ca  thal  
99       2   3     2  
296      1   0     2  
89       1   0     2  
30       2   1     2  
234      1   3     2

In [21]:
clf2.predict(x2_test) #predicted target

array([1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1], dtype=int64)

In [22]:
np.array(y2_test) #original test target

array([1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1], dtype=int64)

In [23]:
#compare prediction and evaluate

In [24]:
y_preds = clf.predict(x2_test)

np.mean(y_preds == y2_test)

0.8852459016393442

In [25]:
clf2.score(x2_test,y2_test)

0.8852459016393442

In [26]:
##

In [27]:
from sklearn.metrics import accuracy_score

In [28]:
accuracy_score(y2_test,y_preds)

0.8852459016393442

In [29]:
####################
#
# predict_proba()
#
################

In [34]:
clf2.predict_proba(x2_test) #probabilities of classifications label  [0,1] [17% for 0, 83% chance for 1]

array([[0.17, 0.83],
       [0.49, 0.51],
       [0.29, 0.71],
       [0.11, 0.89],
       [0.73, 0.27],
       [0.89, 0.11],
       [0.22, 0.78],
       [0.31, 0.69],
       [0.91, 0.09],
       [0.51, 0.49],
       [0.77, 0.23],
       [0.11, 0.89],
       [0.87, 0.13],
       [0.87, 0.13],
       [0.06, 0.94],
       [0.  , 1.  ],
       [0.97, 0.03],
       [0.01, 0.99],
       [0.88, 0.12],
       [0.6 , 0.4 ],
       [0.42, 0.58],
       [0.31, 0.69],
       [0.72, 0.28],
       [0.65, 0.35],
       [0.29, 0.71],
       [0.15, 0.85],
       [0.01, 0.99],
       [0.75, 0.25],
       [0.84, 0.16],
       [0.05, 0.95],
       [0.16, 0.84],
       [0.04, 0.96],
       [0.76, 0.24],
       [0.83, 0.17],
       [0.21, 0.79],
       [0.95, 0.05],
       [0.32, 0.68],
       [0.31, 0.69],
       [0.87, 0.13],
       [0.85, 0.15],
       [0.12, 0.88],
       [0.08, 0.92],
       [0.85, 0.15],
       [0.78, 0.22],
       [0.  , 1.  ],
       [0.35, 0.65],
       [0.82, 0.18],
       [0.29,

In [33]:
clf2.predict(x2_test)

array([1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1], dtype=int64)