In [1]:
import numpy as np
import pandas as pd

In [2]:
hd = pd.read_html('https://github.com/mrdbourke/zero-to-mastery-ml/blob/master/data/heart-disease.csv')[0].iloc[:,1:]

In [3]:
data = hd.copy()

In [45]:
data.to_csv('heart_disease.csv',index=False)

In [4]:
data.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       303 non-null    int64  
 1   sex       303 non-null    int64  
 2   cp        303 non-null    int64  
 3   trestbps  303 non-null    int64  
 4   chol      303 non-null    int64  
 5   fbs       303 non-null    int64  
 6   restecg   303 non-null    int64  
 7   thalach   303 non-null    int64  
 8   exang     303 non-null    int64  
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64  
 11  ca        303 non-null    int64  
 12  thal      303 non-null    int64  
 13  target    303 non-null    int64  
dtypes: float64(1), int64(13)
memory usage: 33.3 KB


In [6]:
## creating Feature and Target

In [7]:
featured_x = data.drop('target',axis=1)
target_y = data['target']

In [8]:
########################## SK Learn ##########################

In [9]:
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.ensemble import RandomForestClassifier



In [10]:
np.random.seed(77)

x_train,x_test,y_train,y_test = train_test_split(featured_x,target_y,test_size=0.2)

clf = RandomForestClassifier()
clf.fit(x_train,y_train)


RandomForestClassifier()

In [11]:
## cross_val_score

In [12]:
np.random.seed(77)

cross_val = cross_val_score(clf,featured_x,target_y,scoring=None)

In [13]:
cross_val

array([0.85245902, 0.8852459 , 0.83606557, 0.81666667, 0.8       ])

In [16]:
#mean
np.mean(cross_val)

0.838087431693989

In [17]:
print(f'Cross Validate Accuracy: {np.mean(cross_val)*100:.2f} %')

Cross Validate Accuracy: 83.81 %


In [20]:
np.random.seed(77)
cross_val2 = cross_val_score(clf,featured_x,target_y,scoring='accuracy')

cross_val2

array([0.85245902, 0.8852459 , 0.83606557, 0.81666667, 0.8       ])

In [21]:
#mean 
np.mean(cross_val2)
print(f'Cross Validate Accuracy with scoring: {np.mean(cross_val2)*100:.2f}%')

Cross Validate Accuracy with scoring: 83.81%


In [22]:
#scoring = 'precision'

In [23]:
np.random.seed(77)
cross_val3 = cross_val_score(clf,featured_x,target_y,scoring='precision')
cross_val3

array([0.83333333, 0.93333333, 0.84848485, 0.84375   , 0.76923077])

In [24]:
#mean 
np.mean(cross_val3)
print(f'Cross validate accuracy with precision: {np.mean(cross_val3)*100:.2f}%')

Cross validate accuracy with precision: 84.56%


In [25]:
# Recall

In [26]:
np.random.seed(77)
cross_val4 = cross_val_score(clf,featured_x,target_y,scoring='recall')
cross_val4

array([0.90909091, 0.84848485, 0.84848485, 0.81818182, 0.90909091])

In [28]:
#mean
np.mean(cross_val4)
print(f'Cross Validate accuracy with recall: {np.mean(cross_val4)*100:.2f} %')

Cross Validate accuracy with recall: 86.67 %


In [29]:
#f1 is a combination of precision and recall

In [30]:
np.random.seed(77)
cross_val5 = cross_val_score(clf,featured_x,target_y,scoring='f1')
print(f'Cross validate accuracy with f1: {np.mean(cross_val5)*100:.2f}%')

Cross validate accuracy with f1: 85.42%


In [31]:
#####################################################
#
# Regression Model 

In [32]:
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestRegressor

In [33]:
data2 = pd.read_csv('../boston.csv')

In [34]:
#feature and target

In [35]:
featured_x2 = data2.drop('target',axis=1)
target_y2 = data2['target']

In [37]:
model = RandomForestRegressor()

In [38]:
np.random.seed(77)
reg_cross_val = cross_val_score(model,featured_x2,target_y2,scoring=None)
reg_cross_val

array([0.76895268, 0.84819146, 0.74966064, 0.48892162, 0.29043609])

In [39]:
np.random.seed(77)
reg_cross_val_r2 =cross_val_score(model,featured_x2,target_y2,scoring='r2')
reg_cross_val_r2

array([0.76895268, 0.84819146, 0.74966064, 0.48892162, 0.29043609])

In [40]:
np.mean(reg_cross_val), np.mean(reg_cross_val_r2)

(0.6292324987066426, 0.6292324987066426)

In [41]:
# MAE ( means_absolute_error)

In [42]:
np.random.seed(77)
reg_cross_val_mae = cross_val_score(model,featured_x2,target_y2,scoring='neg_mean_absolute_error')
reg_cross_val_mae

array([-2.10736275, -2.62121782, -3.38226733, -3.72923762, -3.0929505 ])

In [43]:
# MSE ( means_squared_error)

In [44]:
np.random.seed(77)
reg_cross_val_mse = cross_val_score(model,featured_x2,target_y2,scoring='neg_mean_squared_error')
reg_cross_val_mse

array([ -7.97926419, -13.82015649, -20.04897894, -44.82763114,
       -18.86611014])